import = [
    "~/.config/alacritty/themes/themes/challenger_deep.toml"
]

[font]
size = 18

[window]
opacity = 0.8
blur = true
dynamic_padding = true
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

